services:
  ingestion-api:
    restart: on-failure
    build:
      context: ./ingestion-api
    volumes:
      - ./ingestion-api:/app
      - /app/venv
    ports:
      - "8001:8000"
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - CHUNK_SIZE=$CHUNK_SIZE
      - CHUNK_OVERLAP=$CHUNK_OVERLAP
    depends_on:
      - vectordb

  retrieval-api:
    restart: on-failure
    build:
      context: ./retrieval-api
    volumes:
      - ./retrieval-api:/app
      - /app/venv
    ports:
      - "8002:8000"
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - API_KEY=$ASSESSMENT_API_KEY
      - BASE_URL=$ASSESSMENT_BASE_URL
      - CHAT_MODEL=$ASSESSMENT_CHAT_MODEL
    depends_on:
      - vectordb

  vectordb:
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.0
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"
volumes:
  weaviate_data:
